import {
  User,
  Course,
  CourseSection,
  Lecture,
  Subject,
  BodySystem,
  Question,
  MockExam,
  Order,
  Enrollment,
  NotificationItem,
  Announcement,
  FacultyMember,
  FAQ,
  ContactMessage,
  Coupon,
  AuditLog,
  TestSession,
  UserDevice,
  LoginEvent,
  PaymentEvent,
} from "../types";

export const MOCK_USERS: User[] = [
  {
    id: 1,
    name: "Dr. Hamza Malik",
    email: "student@samsacademy.com",
    phone: "+92 300 1234567",
    role: "student",
    status: "active",
    emailVerifiedAt: "2026-01-10T10:00:00Z",
    twofaEnabled: false,
    lastLoginAt: "2026-07-29T08:30:00Z",
    createdAt: "2026-01-10T10:00:00Z",
    activeDevicesCount: 2,
  },
  {
    id: 2,
    name: "Dr. Zabih Ullah",
    email: "admin@samsacademy.com",
    phone: "+92 301 9876543",
    role: "admin",
    status: "active",
    emailVerifiedAt: "2025-12-01T09:00:00Z",
    twofaEnabled: true,
    lastLoginAt: "2026-07-29T09:15:00Z",
    createdAt: "2025-12-01T09:00:00Z",
    activeDevicesCount: 1,
  },
  {
    id: 3,
    name: "Dr. Ayesha Khan",
    email: "ayesha.k@gmail.com",
    phone: "+92 321 4455667",
    role: "student",
    status: "active",
    emailVerifiedAt: "2026-02-15T11:20:00Z",
    twofaEnabled: true,
    lastLoginAt: "2026-07-28T18:40:00Z",
    createdAt: "2026-02-15T11:20:00Z",
    activeDevicesCount: 1,
  },
  {
    id: 4,
    name: "Dr. Bilal Ahmed",
    email: "bilal.med@hotmail.com",
    phone: "+92 333 7788990",
    role: "student",
    status: "active",
    emailVerifiedAt: "2026-03-20T14:10:00Z",
    twofaEnabled: false,
    lastLoginAt: "2026-07-27T12:05:00Z",
    createdAt: "2026-03-20T14:10:00Z",
    activeDevicesCount: 2,
  },
  {
    id: 5,
    name: "Dr. Sana Fatima",
    email: "sana.fatima@yahoo.com",
    phone: "+92 312 9900112",
    role: "student",
    status: "suspended",
    emailVerifiedAt: "2026-04-05T09:30:00Z",
    twofaEnabled: false,
    lastLoginAt: "2026-06-12T10:15:00Z",
    createdAt: "2026-04-05T09:30:00Z",
    activeDevicesCount: 0,
  },
  {
    id: 6,
    name: "Dr. Usman Ghani",
    email: "usman.g@kemu.edu.pk",
    phone: "+92 304 1122334",
    role: "student",
    status: "active",
    emailVerifiedAt: "2026-05-12T16:00:00Z",
    twofaEnabled: false,
    lastLoginAt: "2026-07-29T11:10:00Z",
    createdAt: "2026-05-12T16:00:00Z",
    activeDevicesCount: 1,
  },
];

export const MOCK_STUDENT_DEVICES: Record<number, UserDevice[]> = {
  1: [
    {
      id: 101,
      userId: 1,
      deviceName: "Windows 11 PC - Chrome 122",
      lastIp: "182.180.122.45",
      location: "Lahore, Pakistan",
      lastSeenAt: "2026-07-29T08:30:00Z",
      isActive: true,
      isCurrent: true,
      fingerprintHash: "fp_win_8f910a3c9b1e",
    },
    {
      id: 102,
      userId: 1,
      deviceName: "Apple iPad Pro - Mobile Safari",
      lastIp: "182.180.122.45",
      location: "Lahore, Pakistan",
      lastSeenAt: "2026-07-28T20:15:00Z",
      isActive: true,
      isCurrent: false,
      fingerprintHash: "fp_ipad_3e211b4a5d",
    },
  ],
  3: [
    {
      id: 103,
      userId: 3,
      deviceName: "MacBook Air M2 - Safari 17.2",
      lastIp: "39.40.112.89",
      location: "Karachi, Pakistan",
      lastSeenAt: "2026-07-28T18:40:00Z",
      isActive: true,
      isCurrent: true,
      fingerprintHash: "fp_mac_1c4b8e9f2a",
    },
  ],
  4: [
    {
      id: 104,
      userId: 4,
      deviceName: "Dell XPS 15 - Firefox 123",
      lastIp: "111.68.100.12",
      location: "Islamabad, Pakistan",
      lastSeenAt: "2026-07-27T12:05:00Z",
      isActive: true,
      isCurrent: true,
      fingerprintHash: "fp_dell_9d8c7b6a",
    },
    {
      id: 105,
      userId: 4,
      deviceName: "Samsung Galaxy Tab S9 - Chrome",
      lastIp: "111.68.100.12",
      location: "Islamabad, Pakistan",
      lastSeenAt: "2026-07-26T14:30:00Z",
      isActive: true,
      isCurrent: false,
      fingerprintHash: "fp_sam_2a3b4c5d",
    },
  ],
};

export const MOCK_LOGIN_EVENTS: Record<number, LoginEvent[]> = {
  1: [
    {
      id: 1,
      userId: 1,
      userName: "Dr. Hamza Malik",
      emailTried: "student@samsacademy.com",
      status: "success",
      ip: "182.180.122.45",
      country: "PK",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/122.0.0.0",
      createdAt: "2026-07-29T08:30:00Z",
    },
    {
      id: 2,
      userId: 1,
      userName: "Dr. Hamza Malik",
      emailTried: "student@samsacademy.com",
      status: "suspicious",
      reason: "New IP Subnet Detected (Riyadh, Saudi Arabia)",
      ip: "185.122.45.10",
      country: "SA",
      userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_3 like Mac OS X) Mobile Safari",
      createdAt: "2026-07-28T14:22:00Z",
    },
    {
      id: 3,
      userId: 1,
      userName: "Dr. Hamza Malik",
      emailTried: "student@samsacademy.com",
      status: "failed",
      reason: "Invalid password attempt",
      ip: "182.180.122.45",
      country: "PK",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/122.0.0.0",
      createdAt: "2026-07-28T08:28:00Z",
    },
    {
      id: 4,
      userId: 1,
      userName: "Dr. Hamza Malik",
      emailTried: "student@samsacademy.com",
      status: "success",
      ip: "182.180.122.45",
      country: "PK",
      userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/122.0.0.0",
      createdAt: "2026-07-27T09:10:00Z",
    },
  ],
};

export const MOCK_PAYMENT_EVENTS: Record<number, PaymentEvent[]> = {
  1: [
    {
      id: 201,
      orderId: 1,
      gateway: "raast",
      eventType: "proof_uploaded",
      externalRef: "RAAST-882103",
      payload: {
        orderId: 1,
        invoiceNo: "SAMS-2026-00101",
        amount: 13500,
        referenceNo: "RAAST-882103",
        note: "Paid via Meezan Mobile App",
        uploadedAt: "2026-07-28T14:25:00Z",
      },
      signatureValid: true,
      createdAt: "2026-07-28T14:25:00Z",
    },
    {
      id: 202,
      orderId: 1,
      gateway: "raast",
      eventType: "manual_approval",
      externalRef: "ADM-APPROVED-101",
      payload: {
        orderId: 1,
        approvedBy: "Dr. Zabih Ullah (Admin)",
        courseActivated: "NRE Step 1 Complete Preparation Masterclass",
        validityDays: 180,
      },
      signatureValid: true,
      createdAt: "2026-07-28T15:00:00Z",
    },
  ],
  2: [
    {
      id: 203,
      orderId: 2,
      gateway: "jazzcash",
      eventType: "ipn_callback",
      externalRef: "JC-TXN-99812341",
      payload: {
        pp_ResponseCode: "000",
        pp_ResponseMessage: "Transaction Successful",
        pp_Amount: "1500000", // in paisas
        pp_TxnRefNo: "JC-TXN-99812341",
        pp_SecureHash: "8F91A2B3C4D5E6F7890123456789ABCD",
      },
      signatureValid: true,
      createdAt: "2026-07-27T09:12:00Z",
    },
  ],
  3: [
    {
      id: 204,
      orderId: 3,
      gateway: "bank_transfer",
      eventType: "proof_uploaded",
      externalRef: "MEZN-INVALID-1102",
      payload: {
        orderId: 3,
        referenceNo: "MEZN-INVALID-1102",
        uploadedAt: "2026-06-15T11:10:00Z",
      },
      signatureValid: true,
      createdAt: "2026-06-15T11:10:00Z",
    },
    {
      id: 205,
      orderId: 3,
      gateway: "bank_transfer",
      eventType: "proof_rejected",
      externalRef: "ADM-REJECTED-103",
      payload: {
        orderId: 3,
        reason: "Invalid transaction reference number. Amount was not received in Meezan Bank account.",
        rejectedBy: "Dr. Zabih Ullah (Admin)",
      },
      signatureValid: true,
      createdAt: "2026-06-15T14:00:00Z",
    },
  ],
};

export const MOCK_SUBJECTS: Subject[] = [
  { id: 1, name: "Anatomy", sortOrder: 1, questionsCount: 12 },
  { id: 2, name: "Physiology", sortOrder: 2, questionsCount: 10 },
  { id: 3, name: "Biochemistry", sortOrder: 3, questionsCount: 8 },
  { id: 4, name: "Pathology", sortOrder: 4, questionsCount: 14 },
  { id: 5, name: "Pharmacology", sortOrder: 5, questionsCount: 12 },
  { id: 6, name: "Microbiology", sortOrder: 6, questionsCount: 8 },
  { id: 7, name: "Medicine", sortOrder: 7, questionsCount: 10 },
  { id: 8, name: "Surgery", sortOrder: 8, questionsCount: 8 },
  { id: 9, name: "Gynae & Obs", sortOrder: 9, questionsCount: 6 },
];

export const MOCK_SYSTEMS: BodySystem[] = [
  { id: 1, name: "Cardiovascular System", sortOrder: 1, questionsCount: 12 },
  { id: 2, name: "Respiratory System", sortOrder: 2, questionsCount: 10 },
  { id: 3, name: "Gastrointestinal System", sortOrder: 3, questionsCount: 8 },
  { id: 4, name: "Renal & Urinary System", sortOrder: 4, questionsCount: 8 },
  { id: 5, name: "Endocrine System", sortOrder: 5, questionsCount: 8 },
  { id: 6, name: "Reproductive System", sortOrder: 6, questionsCount: 6 },
  { id: 7, name: "Musculoskeletal & Skin", sortOrder: 7, questionsCount: 8 },
  { id: 8, name: "Nervous System", sortOrder: 8, questionsCount: 10 },
  { id: 9, name: "Hematology & Oncology", sortOrder: 9, questionsCount: 8 },
  { id: 10, name: "General Principles & Immunology", sortOrder: 10, questionsCount: 10 },
];

export const MOCK_COURSES: Course[] = [
  {
    id: 1,
    title: "NRE Step 1 Complete Preparation Masterclass",
    slug: "nre-step-1-complete",
    examCategory: "NRE1",
    shortDescription: "Comprehensive high-yield medical lectures, QBank integration, and strategic exam prep tailored for PMDC NRE Step 1 candidates.",
    description: "The ultimate preparation program for Pakistan's National Registration Examination (NRE) Step 1. Covering high-yield Organ Systems, Pathology, Pharmacology, and Basic Medical Sciences with system-wise breakdowns, exam techniques, and full QBank access.",
    thumbnailUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80",
    price: 15000,
    currency: "PKR",
    validityDays: 180,
    includesQBank: true,
    isPublished: true,
    sortOrder: 1,
    sectionsCount: 5,
    lecturesCount: 28,
    totalDurationSeconds: 72000,
  },
  {
    id: 2,
    title: "SMLE High-Yield Crash Course (Saudi Medical Licensing)",
    slug: "smle-crash-course",
    examCategory: "SMLE",
    shortDescription: "Focused review program designed specifically for doctors appearing for Saudi Medical Licensing Exam with high-frequency recall topics.",
    description: "Targeted SMLE preparation course covering Saudi Commission for Health Specialties (SCFHS) blueprint. Includes intensive clinical vignette review, ethics, guidelines, and Saudi healthcare standards.",
    thumbnailUrl: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80",
    price: 18000,
    currency: "PKR",
    validityDays: 120,
    includesQBank: true,
    isPublished: true,
    sortOrder: 2,
    sectionsCount: 4,
    lecturesCount: 22,
    totalDurationSeconds: 54000,
  },
  {
    id: 3,
    title: "MBBS Clinical Foundations & Basic Sciences",
    slug: "mbbs-clinical-foundations",
    examCategory: "MBBS",
    shortDescription: "In-depth foundation course for 3rd, 4th & Final Year MBBS students mastering Pathology, Pharmacology & General Medicine.",
    description: "Build robust clinical concept foundations early in your medical career. High-yield video lectures covering General Medicine, Pathology concepts, Pharmacology mechanisms, and ward round clinical skills.",
    thumbnailUrl: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=800&q=80",
    price: 12000,
    currency: "PKR",
    validityDays: 365,
    includesQBank: true,
    isPublished: true,
    sortOrder: 3,
    sectionsCount: 4,
    lecturesCount: 24,
    totalDurationSeconds: 64800,
  },
];

export const MOCK_SECTIONS: CourseSection[] = [
  {
    id: 101,
    courseId: 1,
    title: "Section 1: Cardiovascular Pathology & Pharmacology",
    sortOrder: 1,
    lectures: [
      {
        id: 1001,
        courseId: 1,
        sectionId: 101,
        title: "Lecture 1: Myocardial Infarction & Ischemic Heart Disease",
        description: "Pathophysiology, ECG findings, cardiac markers, and emergency pharmacotherapy.",
        videoProvider: "mock",
        videoRef: "bunny-demo-ref-01",
        durationSeconds: 2700,
        isFreePreview: true,
        isPublished: true,
        sortOrder: 1,
        watchedSeconds: 2700,
        isCompleted: true,
      },
      {
        id: 1002,
        courseId: 1,
        sectionId: 101,
        title: "Lecture 2: Antiarrhythmic Drugs & Cardiac Electrophysiology",
        description: "Vaughan Williams classification, ion channel targets, side effects and clinical indications.",
        videoProvider: "mock",
        videoRef: "bunny-demo-ref-02",
        durationSeconds: 3200,
        isFreePreview: false,
        isPublished: true,
        sortOrder: 2,
        watchedSeconds: 1500,
        isCompleted: false,
      },
      {
        id: 1003,
        courseId: 1,
        sectionId: 101,
        title: "Lecture 3: Valvular Heart Diseases & Murmurs",
        description: "Systolic vs diastolic murmurs, maneuvers, echocardiography findings, and surgical guidelines.",
        videoProvider: "mock",
        videoRef: "bunny-demo-ref-03",
        durationSeconds: 2900,
        isFreePreview: false,
        isPublished: true,
        sortOrder: 3,
      },
    ],
  },
  {
    id: 102,
    courseId: 1,
    title: "Section 2: Respiratory System & Pulmonology",
    sortOrder: 2,
    lectures: [
      {
        id: 1004,
        courseId: 1,
        sectionId: 102,
        title: "Lecture 4: Obstructive vs Restrictive Lung Diseases",
        description: "Spirometry interpretation, asthma vs COPD management ladder, pulmonary fibrosis.",
        videoProvider: "mock",
        videoRef: "bunny-demo-ref-04",
        durationSeconds: 3100,
        isFreePreview: false,
        isPublished: true,
        sortOrder: 1,
      },
      {
        id: 1005,
        courseId: 1,
        sectionId: 102,
        title: "Lecture 5: Pneumonia, Tuberculosis & Pleural Effusions",
        description: "Community acquired vs nosocomial pneumonia, Anti-TB drug regimens and Light's criteria.",
        videoProvider: "mock",
        videoRef: "bunny-demo-ref-05",
        durationSeconds: 3400,
        isFreePreview: false,
        isPublished: true,
        sortOrder: 2,
      },
    ],
  },
  {
    id: 103,
    courseId: 1,
    title: "Section 3: Gastroenterology & Hepatology",
    sortOrder: 3,
    lectures: [
      {
        id: 1006,
        courseId: 1,
        sectionId: 103,
        title: "Lecture 6: Inflammatory Bowel Disease (Crohn's vs Ulcerative Colitis)",
        description: "Pathological differences, extraintestinal manifestations, and biologic therapies.",
        videoProvider: "mock",
        videoRef: "bunny-demo-ref-06",
        durationSeconds: 2800,
        isFreePreview: false,
        isPublished: true,
        sortOrder: 1,
      },
    ],
  },
];

// Generate 60+ realistic medical questions
export const MOCK_QUESTIONS: Question[] = Array.from({ length: 64 }).map((_, index) => {
  const qId = index + 1;
  const subjectObj = MOCK_SUBJECTS[index % MOCK_SUBJECTS.length];
  const systemObj = MOCK_SYSTEMS[index % MOCK_SYSTEMS.length];
  const difficulties: ("easy" | "medium" | "hard")[] = ["easy", "medium", "hard"];
  const difficulty = difficulties[index % 3];

  const vignettes = [
    {
      stem: "A 58-year-old male presents to the emergency department with severe central chest pressure radiating to his left arm for 2 hours. ECG reveals ST-segment elevation in leads II, III, and aVF. Which coronary artery is most likely occluded?",
      options: [
        "Left Anterior Descending Artery (LAD)",
        "Right Coronary Artery (RCA)",
        "Left Circumflex Artery (LCx)",
        "Left Main Coronary Artery",
      ],
      correctIndex: 1,
      explanation: "ST-elevation in lead II, III, and aVF indicates an inferior wall myocardial infarction. The inferior wall of the heart is supplied by the Right Coronary Artery (RCA) in 85–90% of individuals (right-dominant circulation).",
      referenceText: "Harrison's Principles of Internal Medicine, 21st Edition - Chapter 275: Acute Myocardial Infarction.",
    },
    {
      stem: "A 24-year-old female presents with fatigue, cold intolerance, weight gain, and constipation. Physical examination reveals dry skin and delayed relaxation of deep tendon reflexes. TSH is 14.5 mIU/L (High) and free T4 is 0.4 ng/dL (Low). Anti-thyroid peroxidase (anti-TPO) antibodies are strongly positive. What is the primary histological finding associated with this condition?",
      options: [
        "Hurthle cells with lymphocytic infiltrate and germinal centers",
        "Orphan Annie eyes nuclei and psammoma bodies",
        "Granulomatous inflammation with multinucleated giant cells",
        "Follicular hyperplasia with scalloped colloid margins",
      ],
      correctIndex: 0,
      explanation: "This patient has Hashimoto's thyroiditis (chronic lymphocytic thyroiditis). Histology classically demonstrates heavy lymphocytic infiltration, germinal center formation, and Hurthle cells (oxyphilic cells with eosinophilic granular cytoplasm).",
      referenceText: "Robbins & Cotran Pathologic Basis of Disease, 10th Edition - Chapter 24: The Endocrine System.",
    },
    {
      stem: "A 45-year-old male alcoholic presents with confusion, ophthalmoplegia, and ataxia. On examination, horizontal nystagmus is noted. Which co-factor deficiency is directly responsible for these neurological signs?",
      options: [
        "Pyritiamin / Vitamin B6",
        "Thiamine / Vitamin B1",
        "Niacin / Vitamin B3",
        "Cobalamin / Vitamin B12",
      ],
      correctIndex: 1,
      explanation: "Wernicke encephalopathy is caused by severe Thiamine (Vitamin B1) deficiency, commonly seen in chronic alcohol abuse due to poor nutrition and impaired intestinal absorption. Thiamine pyrophosphate is a crucial cofactor for pyruvate dehydrogenase and transketolase.",
      referenceText: "First Aid for the USMLE Step 1 2026 - Biochemistry & Nutrition.",
    },
    {
      stem: "A 32-year-old man presents with chronic bloody diarrhea, lower abdominal cramping, and tenesmus. Colonoscopy reveals continuous mucosal inflammation extending from the rectum up to the splenic flexure with pseudopolyps and loss of haustra. Biopsy shows crypt abscesses. What is the most likely diagnosis?",
      options: [
        "Crohn's Disease",
        "Ulcerative Colitis",
        "Ischemic Colitis",
        "Pseudomembranous Colitis",
      ],
      correctIndex: 1,
      explanation: "Ulcerative Colitis mucosal involvement is continuous starting from the rectum (rectal sparing rules out UC). Histology shows crypt abscesses with neutrophilic infiltrate. Loss of haustra leads to lead-pipe appearance on imaging.",
      referenceText: "Pathoma: Fundamentals of Pathology - Chapter 10: Gastrointestinal Pathology.",
    },
    {
      stem: "A 6-year-old boy presents with periorbital edema, dark tea-colored urine, and hypertension 2 weeks following recovery from a streptococcal pharyngitis. Dipstick urine analysis shows 3+ protein and 4+ blood. Microscopic evaluation demonstrates dysmorphic RBCs and RBC casts. What electron microscopic finding is diagnostic?",
      options: [
        "Subepithelial immune complex 'humps'",
        "Podocyte effacement without immune complexes",
        "Splitting of the glomerular basement membrane ('tram-track')",
        "Linear IgG deposition along the GBM",
      ],
      correctIndex: 0,
      explanation: "Post-streptococcal glomerulonephritis (PSGN) typically develops 1-3 weeks post streptococcal infection. Electron microscopy classically shows large subepithelial immune complex deposits ('humps').",
      referenceText: "Renal Pathology Made Ridiculously Simple - Glomerulonephropathies.",
    },
  ];

  const template = vignettes[index % vignettes.length];

  return {
    id: qId,
    examCategory: "NRE1",
    subjectId: subjectObj.id,
    subjectName: subjectObj.name,
    systemId: systemObj.id,
    systemName: systemObj.name,
    stem: `Q${qId}: ${template.stem} [Case Ref: #${1000 + qId}]`,
    imageUrl: index % 7 === 0 ? "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=600&q=80" : undefined,
    options: template.options.map((opt, oIdx) => ({
      id: qId * 10 + oIdx + 1,
      questionId: qId,
      optionText: opt,
      isCorrect: oIdx === template.correctIndex,
      sortOrder: oIdx + 1,
    })),
    explanation: template.explanation,
    referenceText: template.referenceText,
    difficulty: difficulty,
    isActive: true,
    timesAttempted: 140 + (index * 7) % 300,
    timesCorrect: 95 + (index * 5) % 200,
    isBookmarked: index % 5 === 0,
  };
});

export const MOCK_EXAM_PAPER: MockExam = {
  id: 1,
  title: "NRE Step 1 National Comprehensive Mock Exam 2026",
  examCategory: "NRE1",
  durationMinutes: 60,
  passPercent: 60,
  isPublished: true,
  questionsCount: 50,
  bestScore: 78,
  attemptsCount: 2,
};

export const MOCK_ORDERS: Order[] = [
  {
    id: 1,
    invoiceNo: "SAMS-2026-00101",
    userId: 1,
    userName: "Dr. Hamza Malik",
    userEmail: "student@samsacademy.com",
    courseId: 1,
    courseTitle: "NRE Step 1 Complete Preparation Masterclass",
    amount: 15000,
    discountAmount: 1500,
    finalAmount: 13500,
    currency: "PKR",
    couponCode: "WELCOME10",
    gateway: "easypaisa",
    gatewayRef: "EP-884920194",
    status: "paid",
    paidAt: "2026-01-10T10:15:00Z",
    createdAt: "2026-01-10T10:00:00Z",
  },
  {
    id: 2,
    invoiceNo: "SAMS-2026-00102",
    userId: 1,
    userName: "Dr. Hamza Malik",
    userEmail: "student@samsacademy.com",
    courseId: 2,
    courseTitle: "SMLE High-Yield Crash Course (Saudi Medical Licensing)",
    amount: 18000,
    discountAmount: 0,
    finalAmount: 18000,
    currency: "PKR",
    gateway: "raast",
    gatewayRef: "RAAST-TRX-998231",
    status: "awaiting_verification",
    createdAt: "2026-07-28T14:20:00Z",
    proof: {
      id: 101,
      orderId: 2,
      filePath: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80",
      referenceNo: "RAAST-TRX-998231",
      note: "Paid via HBL Mobile Raast transfer to SAMS Academy account.",
      status: "pending",
      createdAt: "2026-07-28T14:25:00Z",
    },
  },
  {
    id: 3,
    invoiceNo: "SAMS-2026-00099",
    userId: 1,
    userName: "Dr. Hamza Malik",
    userEmail: "student@samsacademy.com",
    courseId: 3,
    courseTitle: "MBBS Clinical Foundations & Basic Sciences",
    amount: 12000,
    discountAmount: 0,
    finalAmount: 12000,
    currency: "PKR",
    gateway: "bank_transfer",
    status: "rejected" as any,
    createdAt: "2026-06-15T11:00:00Z",
    proof: {
      id: 102,
      orderId: 3,
      filePath: "https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&w=600&q=80",
      referenceNo: "MEZN-INVALID-1102",
      note: "Transferred via ATM",
      status: "rejected",
      rejectReason: "Invalid transaction reference number. Amount was not received in Meezan Bank account.",
      createdAt: "2026-06-15T11:10:00Z",
    },
  },
];

export const MOCK_ENROLLMENTS: Enrollment[] = [
  {
    id: 1,
    userId: 1,
    userName: "Dr. Hamza Malik",
    userEmail: "student@samsacademy.com",
    courseId: 1,
    courseTitle: "NRE Step 1 Complete Preparation Masterclass",
    courseThumbnail: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80",
    orderId: 1,
    source: "purchase",
    startsAt: "2026-01-10T10:15:00Z",
    expiresAt: "2026-11-20T10:15:00Z",
    status: "active",
    progressPercent: 42,
    remainingDays: 140,
  },
  {
    id: 2,
    userId: 1,
    userName: "Dr. Hamza Malik",
    userEmail: "student@samsacademy.com",
    courseId: 2,
    courseTitle: "SMLE High-Yield Crash Course (Saudi Medical Licensing)",
    courseThumbnail: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80",
    orderId: 2,
    source: "purchase",
    startsAt: "2026-04-01T10:00:00Z",
    expiresAt: "2026-08-06T10:00:00Z",
    status: "active",
    progressPercent: 78,
    remainingDays: 8, // Expiring soon (<14 days)
  },
  {
    id: 3,
    userId: 1,
    userName: "Dr. Hamza Malik",
    userEmail: "student@samsacademy.com",
    courseId: 3,
    courseTitle: "MBBS Clinical Foundations & Basic Sciences",
    courseThumbnail: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=800&q=80",
    orderId: 3,
    source: "purchase",
    startsAt: "2025-07-01T10:00:00Z",
    expiresAt: "2026-07-01T10:00:00Z",
    status: "expired",
    progressPercent: 100,
    remainingDays: 0, // Expired
  },
];

export const MOCK_ACTIVITIES = [
  {
    id: 1,
    title: "Completed Lecture 1: Myocardial Infarction",
    courseTitle: "NRE Step 1 Complete Preparation Masterclass",
    timestamp: "2 hours ago",
    type: "lecture" as const,
  },
  {
    id: 2,
    title: "Scored 82% in 20-Q Cardiovascular Block",
    courseTitle: "NRE Step 1 QBank",
    timestamp: "Yesterday, 4:30 PM",
    type: "test" as const,
  },
  {
    id: 3,
    title: "Bookmarked Lecture 2: Antiarrhythmic Drugs",
    courseTitle: "NRE Step 1 Complete Preparation Masterclass",
    timestamp: "2 days ago",
    type: "bookmark" as const,
  },
  {
    id: 4,
    title: "Reached 12-Day Active Study Streak milestone!",
    courseTitle: "SAMS Academy Portal",
    timestamp: "3 days ago",
    type: "streak" as const,
  },
];

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 1,
    userId: 1,
    type: "purchase_paid",
    title: "Course Enrollment Active",
    body: "Your enrollment in 'NRE Step 1 Complete Preparation Masterclass' is now active!",
    link: "/app/courses/1",
    isRead: false,
    createdAt: "2026-07-28T10:00:00Z",
  },
  {
    id: 2,
    userId: 1,
    type: "announcement",
    title: "New High-Yield Pathology Lectures Added",
    body: "Section 3 Gastroenterology has been updated with 4 new clinical vignette breakdown videos.",
    link: "/app/courses/1",
    isRead: true,
    createdAt: "2026-07-25T14:30:00Z",
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 1,
    title: "Welcome to SAMS Academy NRE 2026 Session",
    body: "Dear doctors, all NRE Step 1 video modules and high-yield QBank features are fully active. Make sure to schedule your daily practice tests in Exam Mode.",
    audience: "all",
    sendEmail: true,
    createdBy: "Dr. Zabih Ullah",
    createdAt: "2026-07-20T09:00:00Z",
  },
  {
    id: 2,
    title: "Weekly Live QBank Discussion & Clinical Review",
    body: "New clinical vignette breakdowns for Cardiovascular and Renal pathology have been updated in the portal.",
    audience: "course",
    courseId: 1,
    courseTitle: "NRE Step 1 Complete Preparation Masterclass",
    sendEmail: false,
    createdBy: "Dr. Zabih Ullah",
    createdAt: "2026-07-27T11:00:00Z",
  },
];

export const MOCK_FACULTY: FacultyMember[] = [
  {
    id: 1,
    name: "Dr. Zabih Ullah",
    title: "Founder & Lead NRE / USMLE Instructor",
    bio: "MBBS, FCPS Medicine, USMLE Step 1/2CK 250+. Over 8 years teaching basic medical sciences and clinical medicine to over 10,000 NRE and licensing candidates.",
    photoUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    name: "Dr. Ayesha Siddiqui",
    title: "Pathology & Pharmacology Specialist",
    bio: "Gold Medalist MBBS, M.Phil Pathology. Expert in systemic pathology, high-yield organ pathology mechanisms, and drug classifications.",
    photoUrl: "https://images.unsplash.com/photo-1594824813571-27a3f0677161?auto=format&fit=crop&w=400&q=80",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    name: "Dr. Usman Tariq",
    title: "Cardiology & Internal Medicine Lead",
    bio: "FCPS Cardiology, SMLE Certified. Specialist in ECG analysis, valvular lesions, and emergency medical management.",
    photoUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    name: "Dr. Mahnoor Khan",
    title: "Obstetrics & Gynecology Lecturer",
    bio: "MRCOG, FCPS Obs/Gynae. High-yield lecture author for maternal-fetal medicine, reproductive endocrinology, and obstetrical emergencies.",
    photoUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80",
    sortOrder: 4,
    isActive: true,
  },
];

export const MOCK_FAQS: FAQ[] = [
  {
    id: 1,
    question: "How do I access the video lectures and QBank after purchasing?",
    answer: "Once your payment is approved (instant for JazzCash/EasyPaisa; within 1–3 hours for Raast/Bank Transfer), your course will be activated immediately under 'My Courses' in the Student Portal.",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    question: "What is the device policy for SAMS Academy accounts?",
    answer: "To ensure strict content protection, each student account is permitted a maximum of 2 registered devices (e.g. your laptop and mobile). Attempting to log in on a 3rd device will require an administrator reset.",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    question: "Are the QBank questions modeled on the latest PMDC NRE Step 1 blueprint?",
    answer: "Yes, our question bank contains over 3,000 single-best-answer clinical vignettes curated according to PMDC NRE Step 1 and Gulf licensing exam standards, complete with detailed explanations and reference citations.",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    question: "How does the Raast / Bank Transfer payment option work?",
    answer: "Select Raast or Bank Transfer at checkout. The screen will display our official Raast ID / IBAN and QR code. Pay using your mobile banking app, upload a screenshot or transaction reference number, and our team will approve it promptly.",
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 5,
    question: "Can I watch videos offline or download them?",
    answer: "No, all lectures are delivered via high-definition secure adaptive HLS streaming with custom anti-piracy dynamic watermarking to protect proprietary teaching material.",
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 6,
    question: "What is the difference between Practice Mode and Exam Mode in the QBank?",
    answer: "In Practice Mode, you receive immediate feedback and full explanations after every single question. In Exam Mode, answers and timing are timed and scored at the very end to simulate actual exam pressure.",
    sortOrder: 6,
    isActive: true,
  },
];

export const MOCK_CONTACT_MESSAGES: ContactMessage[] = [
  {
    id: 1,
    name: "Dr. Kamran Akram",
    email: "kamran.akram@gmail.com",
    subject: "Inquiry regarding NRE Step 1 Batch 2026",
    message: "Assalamu Alaikum, I would like to confirm if the QBank includes the latest PMDC blueprint updates for Pathology.",
    status: "new",
    createdAt: "2026-07-29T09:15:00Z",
  },
  {
    id: 2,
    name: "Dr. Zainab Tariq",
    email: "zainab.t@kemu.edu.pk",
    subject: "Raast Payment verification help",
    message: "I uploaded my Raast transaction proof for order SAMS-2026-00102. Please verify at your earliest convenience.",
    status: "read",
    createdAt: "2026-07-28T14:20:00Z",
  },
  {
    id: 3,
    name: "Dr. Shahzaib Hasan",
    email: "shahzaib.h@yahoo.com",
    subject: "SMLE Crash Course discount code query",
    message: "Is there a coupon code available for candidates preparing for Gulf Prometric & SMLE exam in August?",
    status: "replied",
    createdAt: "2026-07-26T11:00:00Z",
  },
];

export const MOCK_SETTINGS = {
  site: {
    name: "SAMS Academy",
    tagline: "Premier Medical Exam Preparation Platform",
    supportEmail: "support@samsacademy.com",
    supportPhone: "+92 300 1234567",
    whatsapp: "+92 300 1234567",
    facebookUrl: "https://facebook.com/samsacademy.pk",
    instagramUrl: "https://instagram.com/samsacademy.pk",
    youtubeUrl: "https://youtube.com/@samsacademy",
  },
  payments: {
    bankName: "Meezan Bank Limited",
    accountTitle: "SAMS Medical Academy Pvt Ltd",
    iban: "PK36MEZN0001234567890123",
    accountNumber: "0102-0103456789",
    branchCode: "0102 (Gulberg Branch, Lahore)",
    raastId: "03001234567",
    raastIban: "PK36MEZN0001234567890123",
    raastQrImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=400&q=80",
    enabledGateways: ["jazzcash", "easypaisa", "raast", "bank_transfer"],
    gatewayKeys: {
      jazzcashMerchantId: "MC_JAZZ_987654",
      jazzcashPassword: "••••••••••••",
      jazzcashIntegritySalt: "••••••••••••••••",
      easypaisaStoreId: "EP_STORE_44321",
      easypaisaHashKey: "••••••••••••••••",
      payfastMerchantId: "PF_MERCHANT_1122",
      payfastSecuredKey: "••••••••••••••••",
      safepayApiKey: "sec_live_sf_998877",
      safepaySecret: "••••••••••••••••",
    },
  },
  video: {
    bunnyLibraryId: "248910",
    bunnyApiKey: "••••••••-••••-••••-••••-••••••••••••",
    bunnyTokenAuthKey: "••••••••••••••••••••••••••••••••",
    bunnyCdnHostname: "video.samsacademy.com",
  },
  smtp: {
    host: "smtp.hostinger.com",
    port: "465",
    user: "noreply@samsacademy.com",
    password: "••••••••••••",
    fromName: "SAMS Academy Notifications <noreply@samsacademy.com>",
    secure: true,
  },
  legal: {
    privacyPolicy: `# Privacy Policy\n\nAt SAMS Academy, accessible from https://samsacademy.com, one of our main priorities is the privacy of our candidates and medical doctors...\n\n### 1. Information We Collect\nWe collect personal details such as Name, Email, Phone number, and device hardware signatures strictly for authentication and DRM content protection.\n\n### 2. How We Use Your Information\nYour data is used to provide access to secure video courses, track QBank performance, process order invoices, and prevent unauthorized credential sharing.`,
    termsAndConditions: `# Terms and Conditions\n\nWelcome to SAMS Academy. By purchasing or using our medical exam preparation portal, you agree to comply with the following terms...\n\n### 1. Single User License & Device Binding\nEach candidate account is limited to a maximum of 2 active personal devices. Shared access, recording, downloading, or broadcasting teaching material is strictly prohibited under medical copyright laws.\n\n### 2. Refund & Cancellation Policy\nCourse enrollments and QBank subscriptions are non-refundable once content access is granted.`,
    refundPolicy: `# Refund & Cancellation Policy\n\nSAMS Academy offers premium medical preparation courses. Please review our policy prior to enrollment...\n\n### 1. Refund Eligibility\nDue to instant digital delivery of proprietary video lectures and QBank vignettes, fees paid are non-refundable once payment is confirmed.`,
  },
};

export const MOCK_COUPONS: Coupon[] = [
  {
    id: 1,
    code: "WELCOME10",
    type: "percent",
    value: 10,
    usedCount: 42,
    maxUses: 100,
    isActive: true,
  },
  {
    id: 2,
    code: "RAMADAN20",
    type: "percent",
    value: 20,
    usedCount: 15,
    maxUses: 50,
    isActive: true,
  },
  {
    id: 3,
    code: "FLAT2000",
    type: "fixed",
    value: 2000,
    usedCount: 8,
    maxUses: 30,
    isActive: true,
  },
  {
    id: 4,
    code: "EXPIRED20",
    type: "percent",
    value: 20,
    usedCount: 10,
    maxUses: 50,
    isActive: false, // Expired
  },
  {
    id: 5,
    code: "FULL100",
    type: "percent",
    value: 15,
    usedCount: 50,
    maxUses: 50, // Exhausted/used up
    isActive: true,
  },
];

export const MOCK_TEST_SESSIONS: TestSession[] = [
  {
    id: 101,
    userId: 1,
    mode: "practice",
    examCategory: "NRE1",
    questionCount: 20,
    status: "in_progress",
    startedAt: "2026-07-29T10:30:00Z",
    correctCount: 8,
    incorrectCount: 2,
    skippedCount: 10,
    timeRemainingSeconds: 1200,
  },
  {
    id: 102,
    userId: 1,
    mode: "exam",
    examCategory: "NRE1",
    questionCount: 40,
    timeLimitSeconds: 3600,
    status: "completed",
    startedAt: "2026-07-28T15:00:00Z",
    completedAt: "2026-07-28T15:52:00Z",
    correctCount: 33,
    incorrectCount: 5,
    skippedCount: 2,
    scorePercent: 82,
    passed: true,
  },
  {
    id: 103,
    userId: 1,
    mode: "practice",
    examCategory: "NRE1",
    questionCount: 10,
    status: "completed",
    startedAt: "2026-07-26T11:00:00Z",
    completedAt: "2026-07-26T11:20:00Z",
    correctCount: 7,
    incorrectCount: 3,
    skippedCount: 0,
    scorePercent: 70,
    passed: true,
  },
  {
    id: 104,
    userId: 1,
    mode: "exam",
    examCategory: "NRE1",
    questionCount: 20,
    timeLimitSeconds: 1800,
    status: "abandoned",
    startedAt: "2026-07-24T09:15:00Z",
    correctCount: 4,
    incorrectCount: 6,
    skippedCount: 10,
    scorePercent: 20,
    passed: false,
  },
];

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: 1,
    actorUserId: 2,
    actorName: "Dr. Zabih Ullah (Admin)",
    action: "course.update",
    entityType: "Course",
    entityId: 1,
    summary: "Updated price and published NRE Step 1 Complete Preparation Masterclass",
    ip: "182.180.122.45",
    createdAt: "2026-07-28T16:40:00Z",
  },
  {
    id: 2,
    actorUserId: 2,
    actorName: "Dr. Zabih Ullah (Admin)",
    action: "order.approve_transfer",
    entityType: "Order",
    entityId: 1,
    summary: "Approved Raast manual payment for order SAMS-2026-00101",
    ip: "182.180.122.45",
    createdAt: "2026-07-27T10:15:00Z",
  },
];
